secrets:
  db_password: db_password.txt

services:
  proxy:
    build:
      context: ./proxy
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - backend-network
      - frontend-network
    container_name: proxy
    secrets:
      - db_password
  frontend:
    image: pawelkonior/images_frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - frontend-network
    stdin_open: true
    container_name: vue
  backend:
    build: ./backend
#    ports:
#      - "8000:8000"
    restart: "on-failure"
#    container_name: django
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/env/.env
    depends_on:
      - db-postgres
      - db-cache
    networks:
      - backend-network
      - db-postgres-network
      - db-cache-network
  db-postgres:
    image: postgres
    ports:
      - "5434:5432"
    env_file:
      - ./backend/env/.env
    volumes:
      - postgres-dj:/var/lib/postgresql/data
    container_name: postgres_django
    networks:
      - db-postgres-network
  db-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - db-cache-network
    container_name: redis_django

volumes:
  postgres-dj:
  redisdata:
  static_volume:
  media_volume:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  db-postgres-network:
    driver: bridge
  db-cache-network:
    driver: bridge