# Generated by Django 4.0.3 on 2022-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.FileField(upload_to='resized_images/'),
        ),
    ]
